### ISSUE TITLE
Implement the nonograms game 🎯

### ISSUE THREAD

**Issue by boroboro01** [boroboro01/Nonograms#1]
# Description
Implement the nonograms game for Mobile Programming Project

# Tasks
- [x] Design the UI
- [x] Create a black square
- [x] Create the `Cell` class
- [x] Implement game control logic
- [x] Test the game

# Example
![image](https://github.com/user-attachments/assets/244dd416-2be9-49e7-8302-df73439b9a47)
